/**
 * Biome names by id. 1.7.10 sends a chunk's biomes as 256 bytes, one id per column (index
 * z << 4 | x), and the protocol never names them; nor does Forge's registry handshake, which
 * names only blocks and items. So the names come from this table:
 *  - vanilla 1.7.10 (BiomeGenBase): ids 0-39 and the "M" variants at id + 128;
 *  - the GTNH 2.8.4 test server's configured mod biomes, read from its config on 2026-09-30:
 *    BiomesOPlenty (biomesoplenty/ids.cfg), Realistic World Gen (RWG.cfg; the server's world
 *    generator), Thaumcraft (Thaumcraft.cfg), BuildCraft (buildcraft/main.cfg), GT++
 *    (GTPlusPlus.cfg) and Applied Energistics 2 (its storage dimension).
 * Checked against the test world's region files (agent-test/region, 654 chunks, 2026-09-30):
 * every id found there is named here: 230 Hot Desert around spawn, then 229 Hot Forest, 43
 * Bamboo Forest, 211 River Oasis, 49 Canyon, 209 Wet River, 190 Eerie and 207 Hot River.
 * A server with other mod biome ids shows them as "biome #<id>".
 */
const VANILLA: ReadonlyArray<[number, string]> = [
  [0, 'Ocean'],
  [1, 'Plains'],
  [2, 'Desert'],
  [3, 'Extreme Hills'],
  [4, 'Forest'],
  [5, 'Taiga'],
  [6, 'Swampland'],
  [7, 'River'],
  [8, 'Hell'],
  [9, 'Sky'],
  [10, 'FrozenOcean'],
  [11, 'FrozenRiver'],
  [12, 'Ice Plains'],
  [13, 'Ice Mountains'],
  [14, 'MushroomIsland'],
  [15, 'MushroomIslandShore'],
  [16, 'Beach'],
  [17, 'DesertHills'],
  [18, 'ForestHills'],
  [19, 'TaigaHills'],
  [20, 'Extreme Hills Edge'],
  [21, 'Jungle'],
  [22, 'JungleHills'],
  [23, 'JungleEdge'],
  [24, 'Deep Ocean'],
  [25, 'Stone Beach'],
  [26, 'Cold Beach'],
  [27, 'Birch Forest'],
  [28, 'Birch Forest Hills'],
  [29, 'Roofed Forest'],
  [30, 'Cold Taiga'],
  [31, 'Cold Taiga Hills'],
  [32, 'Mega Taiga'],
  [33, 'Mega Taiga Hills'],
  [34, 'Extreme Hills+'],
  [35, 'Savanna'],
  [36, 'Savanna Plateau'],
  [37, 'Mesa'],
  [38, 'Mesa Plateau F'],
  [39, 'Mesa Plateau'],
  [129, 'Sunflower Plains'],
  [130, 'Desert M'],
  [131, 'Extreme Hills M'],
  [132, 'Flower Forest'],
  [133, 'Taiga M'],
  [134, 'Swampland M'],
  [140, 'Ice Plains Spikes'],
  [149, 'Jungle M'],
  [151, 'JungleEdge M'],
  [155, 'Birch Forest M'],
  [156, 'Birch Forest Hills M'],
  [157, 'Roofed Forest M'],
  [158, 'Cold Taiga M'],
  [160, 'Mega Spruce Taiga'],
  [161, 'Redwood Taiga Hills M'],
  [162, 'Extreme Hills+ M'],
  [163, 'Savanna M'],
  [164, 'Savanna Plateau M'],
  [165, 'Mesa (Bryce)'],
  [166, 'Mesa Plateau F M'],
  [167, 'Mesa Plateau M'],
];

/** biomesoplenty/ids.cfg ("<Name> ID" = id). */
const BIOMES_O_PLENTY: ReadonlyArray<[number, string]> = [
  [40, 'Alps Forest'],
  [41, 'Alps'],
  [42, 'Arctic'],
  [43, 'Bamboo Forest'],
  [44, 'Bayou'],
  [45, 'Bog'],
  [47, 'Boreal Forest'],
  [48, 'Brushland'],
  [49, 'Canyon'],
  [50, 'Canyon Ravine'],
  [51, 'Chaparral'],
  [52, 'Cherry Blossom Grove'],
  [53, 'Coniferous Forest'],
  [54, 'Coral Reef'],
  [56, 'Crag'],
  [57, 'Dead Forest'],
  [58, 'Dead Swamp'],
  [59, 'Deciduous Forest'],
  [60, 'Dry River'],
  [61, 'Eucalyptus Forest'],
  [62, 'Fen'],
  [63, 'Flower Field'],
  [64, 'Frost Forest'],
  [65, 'Fungi Forest'],
  [66, 'Garden'],
  [67, 'Glacier'],
  [68, 'Grassland'],
  [69, 'Grove'],
  [70, 'Heathland'],
  [71, 'Highland'],
  [72, 'Jade Cliffs'],
  [73, 'Kelp Forest'],
  [74, 'Land of Lakes'],
  [75, 'Land of Lakes Marsh'],
  [76, 'Lavender Fields'],
  [77, 'Lush Desert'],
  [78, 'Lush River'],
  [79, 'Lush Swamp'],
  [80, 'Mangrove'],
  [81, 'Maple Woods'],
  [82, 'Marsh'],
  [83, 'Meadow Forest'],
  [84, 'Meadow'],
  [85, 'Moor'],
  [86, 'Mountain'],
  [87, 'Mystic Grove'],
  [88, 'Oasis'],
  [89, 'Ominous Woods'],
  [90, 'Orchard'],
  [91, 'Origin Valley'],
  [92, 'Outback'],
  [94, 'Polar Chasm'],
  [95, 'Prairie'],
  [96, 'Quagmire'],
  [97, 'Rainforest'],
  [98, 'Redwood Forest'],
  [99, 'Sacred Springs'],
  [100, 'Scrubland'],
  [101, 'Seasonal Forest Clearing'],
  [102, 'Seasonal Forest'],
  [103, 'Shield'],
  [104, 'Shrubland'],
  [105, 'Silkglades'],
  [106, 'Sludgepit'],
  [107, 'Snowy Coniferous Forest'],
  [108, 'Spectral Garden'],
  [109, 'Spruce Woods'],
  [110, 'Steppe'],
  [111, 'Temperate Rainforest'],
  [112, 'Thicket'],
  [113, 'Tropical Rainforest'],
  [114, 'Tropics'],
  [115, 'Tundra'],
  [117, 'Visceral Heap'],
  [118, 'Volcano'],
  [119, 'Wasteland'],
  [120, 'Wetland'],
  [121, 'Woodland'],
  [122, 'Xeric Shrubland'],
  [123, 'Dense Forest'],
  [128, 'Boneyard'],
  [136, 'Corrupted Sands'],
  [137, 'Phantasmagoric Inferno'],
  [138, 'Undergarden'],
];

/** RWG.cfg "biome ids" (the test world is generated by Realistic World Gen). */
const REALISTIC_WORLD_GEN: ReadonlyArray<[number, string]> = [
  [200, 'Ice River'],
  [202, 'Cold River'],
  [205, 'Temperate River'],
  [207, 'Hot River'],
  [209, 'Wet River'],
  [211, 'River Oasis'],
  [213, 'Ice Ocean'],
  [214, 'Cold Ocean'],
  [216, 'Temperate Ocean'],
  [218, 'Hot Ocean'],
  [223, 'Ocean Oasis'],
  [224, 'Snow Desert'],
  [225, 'Snow Forest'],
  [226, 'Cold Plains'],
  [227, 'Cold Forest'],
  [228, 'Hot Plains'],
  [229, 'Hot Forest'],
  [230, 'Hot Desert'],
  [231, 'Plains (RWG)'],
  [232, 'Tropical Island'],
  [233, 'Redwood'],
  [234, 'Jungle (RWG)'],
  [235, 'Oasis (RWG)'],
  [236, 'Temperate Forest'],
  [237, 'Wet Ocean'],
];

const OTHER_MODS: ReadonlyArray<[number, string]> = [
  [126, 'Oil Ocean'], // BuildCraft
  [127, 'Oil Desert'], // BuildCraft
  [135, 'Storage Cell'], // Applied Energistics 2 (its own dimension)
  [190, 'Eerie'], // Thaumcraft
  [191, 'Eldritch Lands'], // Thaumcraft
  [192, 'Magical Forest'], // Thaumcraft
  [193, 'Taint'], // Thaumcraft
  [199, 'Everglades'], // GT++ (its own dimension)
];

export const BIOME_NAMES: ReadonlyMap<number, string> = new Map([
  ...VANILLA,
  ...BIOMES_O_PLENTY,
  ...REALISTIC_WORLD_GEN,
  ...OTHER_MODS,
]);

/** The value of a column whose biome the server has not set. */
export const UNSET_BIOME = 255;

export function biomeName(id: number): string {
  return BIOME_NAMES.get(id) ?? `biome #${id}`;
}
